### ISSUE TITLE
🕐-2 Market research for tools like AI Verify

### ISSUE THREAD

**Issue by uittenbroekrobbert** [MinBZK/ai-validation#45]
We don't need to measure all the tools against the checklist of [ticket](https://github.com/orgs/MinBZK/projects/7/views/3?pane=issue&itemId=53491327), as this will costs too much time, unless we all think it is useful.

Open Source tool from Belgie: https://altai.ai4belgium.be/

Create tickets for each of the tools that we'd like to apply our [checklist](https://github.com/orgs/MinBZK/projects/7/views/3?pane=issue&itemId=53491327)

**Comment by berrydenhartog** [comment]
'Welcome to our community :hugs: and thank you for your first contribution.
              Please make sure to review our [contribution guidelines](CONTRIBUTE.md) :heart:'

**Comment by berrydenhartog** [comment]
'Welcome to our community :hugs: and thank you for your first contribution.
              Please make sure to review our [contribution guidelines](blob/master/CONTRIBUTE.md) :heart:'
